#@url = https://8080-marcoweb-apiquiz20242-us2tnb4btx5.ws-us116.gitpod.io

@url = http://localhost:8080
 

###
GET {{url}}/colaborador

###
GET {{url}}/colaborador/1

###
POST {{url}}/colaborador
Content-Type: application/json

{
    "nome": "Fulano"
}

###
POST {{url}}/colaborador
Content-Type: application/json

{
    "nome": "Paulo"
}

###
PUT {{url}}/colaborador/2
Content-Type: application/json

{
    "nome": "Paulo"
}

###
DELETE {{url}}/colaborador/1