@url = http://localhost:8080
 

###
GET {{url}}/tarefa


###
GET {{url}}/tarefa/1

###
POST {{url}}/tarefa
Content-Type: application/json

{
    "titulo": "Testandp",
    "descricao": "Descricao",
    "dataInicio": "2024-08-05",
    "dataConclusao": "2024-09-12"
}

###
POST {{url}}/tarefa
Content-Type: application/json

{
    "titulo": "Tarefa Y",
    "descricao": "Descricao Tarefa Y",
    "dataInicio": "2024-04-09",
    "dataConclusao": "2024-06-20"
}

###
POST {{url}}/tarefa
Content-Type: application/json

{
    "titulo": "Tarefa Z",
    "descricao": "Descricao Tarefa Z",
    "dataInicio": "2024-11-02",
    "dataConclusao": "2024-12-12"
}

###
PUT {{url}}/tarefa/1
Content-Type: application/json

{
    "titulo": "Tarefa Y-A"
}

###
DELETE {{url}}/tarefa/1

###
POST {{url}}/tarefa/3/colaboradores/2

###
DELETE {{url}}/tarefa/3/colaboradores/2